package me.guyliangilsing.attractions_databasemicroserviceattraction_data;

import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class AttractionsDatabaseMicroserviceAttractionDataApplicationTests{
}
