name: "Build, test, and deploy the main branche"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Go to this branche"
        uses: 'actions/checkout@v1'
      - name: "Set up JDK 11"
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: "Create property files"
        run: |
            'touch ./src/main/resources/application.properties'
            'echo "server.servlet.context-path=/api/v1" >> ./src/main/resources/application.properties'
            'echo "spring.datasource.url=jdbc:mysql://db/adb-attractions-service" >> ./src/main/resources/application.properties'
            'echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> ./src/main/resources/application.properties'
            'echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> ./src/main/resources/application.properties'
            'echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> ./src/main/resources/application.properties'
            'echo "spring.jpa.hibernate.ddl-auto=update" >> ./src/main/resources/application.properties'
            'echo "spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect" >> ./src/main/resources/application.properties'

            'touch ./src/test/resources/application.properties'
            'echo "spring.datasource.driver-class-name=org.h2.Driver" >> ./src/test/resources/application.properties'
            'echo "spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1" >> ./src/test/resources/application.properties'
            'echo "spring.datasource.username=root" >> ./src/test/resources/application.properties'
            'echo "spring.datasource.password=" >> ./src/test/resources/application.properties'
      - name: "Run maven commands"
        run: |
            'mvnw clean install'
            'mvnw spring-boot:test'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        run: |
            export DOCKER_BUILDKIT=0
            export COMPOSE_DOCKER_CLI_BUILD=0
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/adb-service-attractions:latest .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/adb-service-attractions:latest
