name: "Build, test, and deploy the main branche"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Go to this branche"
        uses: 'actions/checkout@v1'
      - name: "Set up JDK 11"
        uses: 'actions/setup-java@v2'
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: "Create main property file"
        uses: 'finnp/create-file-action@master'
        env:
          FILE_NAME: 'src/main/resources/application.properties'
          FILE_DATA: 
            server.servlet.context-path=/api/v1\n
            spring.datasource.url=jdbc:mysql://127.0.0.1:3306/adb-attractions-service\n
            spring.datasource.username=${{ secrets.DB_USERNAME }}\n
            spring.datasource.password=${{ secrets.DB_PASSWORD }}\n
            spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\n
            spring.jpa.hibernate.ddl-auto=update\n
            spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect\n
      - name: "Create test property file"
        uses: 'finnp/create-file-action@master'
        env:
          FILE_NAME: 'src/test/resources/application.properties'
          FILE_DATA:
            spring.datasource.driver-class-name=org.h2.Driver\n
            spring.datasource.url=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1\n
            spring.datasource.username=root\n
            spring.datasource.password=\n
      - name: "Run maven commands"
        run: |
            'mvnw clean install'
            'mvnw spring-boot:test'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        run: |
            export DOCKER_BUILDKIT=0
            export COMPOSE_DOCKER_CLI_BUILD=0
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/adb-service-attractions:latest .
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/adb-service-attractions:latest
